// Beleaf Typography Render Service
// -----------------------------------------------------------------
// A tiny HTTP service that takes a source product photo + the
// Design Template JSON from `16_DESIGN_BIBLE` + the headline/overlay
// text generated by Workflow 2, and returns a PNG with Thai
// typography drawn by a real headless browser (Playwright/Chromium)
// using real Google Fonts -- never a generative-AI guess at glyph
// shapes, so Thai tone marks / vowels always come out correct.
//
// Deploy this on Render.com / Railway / Fly.io / any small VPS.
// n8n Cloud calls it over plain HTTPS -- no Puppeteer/Playwright
// needs to run inside n8n itself.
// -----------------------------------------------------------------

const express = require("express");
const { chromium } = require("playwright");

const app = express();
app.use(express.json({ limit: "25mb" }));

const PORT = process.env.PORT || 3000;
const AUTH_TOKEN = process.env.RENDER_AUTH_TOKEN || ""; // set this in your host's env vars

const GOOGLE_FONT_FAMILIES = [
  "Anuphan:wght@400;700;800;900",
  "IBM+Plex+Sans+Thai:wght@400;500;600;700",
  "Sarabun:wght@400;500;700",
  "Mitr:wght@400;500;600;700",
  "Prompt:wght@400;500;700;800",
  "Kanit:wght@400;500;700;800;900",
];

function fontFamilyCss(name) {
  const base = String(name || "").replace(
    /\s*(Thin|Light|Regular|Medium|SemiBold|Bold|ExtraBold|Black)\s*$/i,
    ""
  ).trim();
  if (/^IBM Plex Thai/i.test(base)) return "IBM Plex Sans Thai";
  return base || "Noto Sans Thai";
}

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Same as escapeHtml, but preserves literal "\n" as a line break. Lets a
// single banner or bubble hold 2 lines (e.g. a checklist bubble with two
// "✅ ..." items, or a headline + subline banner) without a new layout
// mode -- this covers several competitor patterns that are really just
// "existing shape, multi-line content" rather than a different structure.
function escapeMultiline(s) {
  return escapeHtml(s).replace(/\n/g, "<br/>");
}

function readableTextColor(hex) {
  const h = String(hex || "#888888").replace("#", "");
  const r = parseInt(h.substring(0, 2), 16) || 0;
  const g = parseInt(h.substring(2, 4), 16) || 0;
  const b = parseInt(h.substring(4, 6), 16) || 0;
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.6 ? "#1C1C1E" : "#FFFFFF";
}

const SLOT_CSS = {
  top_left: "top:6%; left:6%;",
  top_right: "top:6%; right:6%;",
  bottom_left: "bottom:6%; left:6%;",
  bottom_right: "bottom:6%; right:6%;",
};

// Fixed 6-slot grid used by the "bubble_grid" structure type (two columns
// of three, straddling the product photo). Kept separate from SLOT_CSS
// (4 corners) so the default "bubble_corner" layout is untouched.
const GRID_SLOT_CSS = [
  "top:22%; left:5%;",
  "top:22%; right:5%;",
  "top:44%; left:5%;",
  "top:44%; right:5%;",
  "top:66%; left:5%;",
  "top:66%; right:5%;",
];

function buildHtml({ imageDataUrl, design, headline, overlayText, imageSequence, imageCount }) {
  const template = design.designTemplate || {};
  const banner = template.banner || {};
  const bubble = template.bubble || {};
  const badge = template.badge || {};
  const decoration = Array.isArray(template.decoration) ? template.decoration : [];
  const structureType = String(template.structureType || "").toLowerCase();

  const bannerColorKey = banner.defaultAccentKey || "trust";
  const bannerColor = (banner.palette && banner.palette[bannerColorKey]) || "#1C1C1E";
  const bannerTextColor = readableTextColor(bannerColor);
  const bannerHeight = Number(banner.heightPercent || 14);
  const bannerOnBottom = banner.position === "bottom";
  const bannerPos = bannerOnBottom ? "bottom:0;" : "top:0;";
  const headlineFont = fontFamilyCss(banner.font || design["Font Headline"]);
  const headlineWeight = Number(banner.weight || design["Headline Weight"] || 800);

  // Optional: banner as a compact rounded "tag" instead of a full-width
  // bar -- covers the common competitor pattern of a small colored pill
  // in a corner rather than a strip across the whole image. Defaults
  // (100% width, centered) reproduce the exact previous behavior, so
  // this is purely additive and every existing page is unaffected.
  const bannerWidthPercent = Number(banner.widthPercent || 100);
  const bannerAlign = String(banner.align || "center").toLowerCase();
  const bannerIsTag = bannerWidthPercent < 100;
  const bannerHCss = bannerIsTag
    ? (bannerAlign === "left" ? "left:6%;" : bannerAlign === "right" ? "right:6%;" : "left:50%; transform:translateX(-50%);")
    : "left:0;";
  const bannerRadius = bannerIsTag ? (banner.cornerRadius ? `${banner.cornerRadius}px` : "18px") : "0";

  const bodyFont = fontFamilyCss(bubble.font || design["Font Body"]);
  const bubbleShape = bubble.shape === "pill" ? "999px" : "16px";
  const bubbleBg = bubble.background || "#F5F0E1";
  const bubbleText = bubble.textColor || "#3E2723";
  const underline = decoration.includes("underline") ? "text-decoration: underline; text-decoration-thickness: 3px;" : "";

  // -------------------------------------------------------------
  // Structure branch: three layout modes share the same banner/
  // badge/product-photo scaffolding below, but differ in how the
  // overlayText items are placed. Unknown/empty structureType falls
  // through to "bubble_corner" (the original, unchanged behavior).
  // -------------------------------------------------------------
  let bubblesHtml = "";
  let paragraphHtml = "";

  if (structureType === "bubble_grid") {
    // Up to 6 short items scattered in a 2-column x 3-row grid.
    const items = (overlayText || []).slice(0, GRID_SLOT_CSS.length);
    bubblesHtml = items
      .map((text, i) => {
        const posCss = GRID_SLOT_CSS[i] || GRID_SLOT_CSS[GRID_SLOT_CSS.length - 1];
        return `<div class="bubble bubble-grid" style="${posCss} background:${bubbleBg}; color:${bubbleText}; font-family:'${bodyFont}', sans-serif; border-radius:${bubbleShape}; ${underline}">${escapeMultiline(text)}</div>`;
      })
      .join("\n");
  } else if (structureType === "paragraph_left") {
    // One flowing multi-line paragraph in a panel on the left third,
    // instead of discrete bubbles. overlayText[0] holds the full text;
    // it may contain literal newlines to control line breaks.
    const paraText = String((overlayText && overlayText[0]) || "").trim();
    const lines = paraText.split(/\n+/).map((l) => l.trim()).filter(Boolean);
    const linesHtml = lines.map((l) => `<div class="para-line">${escapeHtml(l)}</div>`).join("\n");
    const panelTop = bannerOnBottom ? "4%" : `calc(${bannerHeight}% + 4%)`;
    const panelBottom = bannerOnBottom ? `calc(${bannerHeight}% + 4%)` : "4%";
    paragraphHtml = lines.length
      ? `<div class="para-panel" style="top:${panelTop}; bottom:${panelBottom}; background:${bubbleBg}; color:${bubbleText}; font-family:'${bodyFont}', sans-serif;">${linesHtml}</div>`
      : "";
  } else {
    // Default: original "bubble_corner" behavior, unchanged.
    const maxCount = Number(bubble.maxCount || 3);
    const slots = (bubble.allowedSlots && bubble.allowedSlots.length
      ? bubble.allowedSlots
      : ["top_left", "top_right", "bottom_left", "bottom_right"]
    ).slice(0, maxCount);

    const bubbleItems = (overlayText || []).slice(0, slots.length);

    bubblesHtml = bubbleItems
      .map((text, i) => {
        const slotCss = SLOT_CSS[slots[i]] || SLOT_CSS.bottom_right;
        return `<div class="bubble" style="${slotCss} background:${bubbleBg}; color:${bubbleText}; font-family:'${bodyFont}', sans-serif; border-radius:${bubbleShape}; ${underline}">${escapeMultiline(text)}</div>`;
      })
      .join("\n");
  }

  const badgeHtml = badge.text
    ? `<div class="badge" style="background:${badge.color || "#FFD1A3"}; color:${readableTextColor(badge.color || "#FFD1A3")}; font-family:'${bodyFont}', sans-serif; border-radius:${badge.type === "pill" ? "999px" : "10px"};">${escapeHtml(badge.text)}</div>`
    : "";

  const fontLinks = GOOGLE_FONT_FAMILIES.map((f) => `family=${f}`).join("&");

  // headline may contain a literal "\n" for an optional 2nd, smaller
  // "subline" (e.g. "ปอดแข็งแรง\nหายใจโล่งขึ้น ลดหอบหืด") -- covers the
  // competitor "corner tag" banners that pack a bold word + a short
  // supporting phrase into the same banner without a new structure type.
  const [headlineMain, ...headlineRest] = String(headline || "").split("\n");
  const headlineSub = headlineRest.join(" ").trim();
  const headlineHtml = headlineSub
    ? `${escapeHtml(headlineMain)}<div class="banner-sub">${escapeHtml(headlineSub)}</div>`
    : escapeHtml(headlineMain);

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?${fontLinks}&display=swap" rel="stylesheet">
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  html, body { width:1080px; height:1080px; overflow:hidden; }
  .canvas {
    position:relative; width:1080px; height:1080px;
    background-image:url('${imageDataUrl}');
    background-size:cover; background-position:center;
  }
  .banner {
    position:absolute; width:${bannerWidthPercent}%; ${bannerHCss} ${bannerPos}
    ${bannerIsTag ? "margin:3% 0;" : ""}
    height:${bannerHeight}%;
    background:${bannerColor}; color:${bannerTextColor};
    display:flex; flex-direction:column; align-items:center; justify-content:center;
    text-align:center; padding:0 6%;
    font-family:'${headlineFont}', sans-serif; font-weight:${headlineWeight};
    font-size:${bannerIsTag ? "40px" : "56px"}; line-height:1.15;
    border-radius:${bannerRadius};
  }
  .banner .banner-sub {
    font-size:${bannerIsTag ? "24px" : "30px"}; font-weight:500; margin-top:6px;
  }
  .bubble {
    position:absolute; max-width:38%;
    padding:16px 22px; font-size:30px; font-weight:600; line-height:1.3;
  }
  .bubble-grid {
    max-width:40%; padding:12px 18px; font-size:26px;
  }
  .para-panel {
    position:absolute; left:4%; width:34%;
    padding:26px 24px; border-radius:20px;
    display:flex; flex-direction:column; justify-content:center; gap:12px;
  }
  .para-line {
    font-size:28px; font-weight:600; line-height:1.5;
  }
  .badge {
    position:absolute; bottom:6%; right:6%;
    padding:10px 20px; font-size:26px; font-weight:700;
  }
  .seq {
    position:absolute; bottom:2%; left:2%; font-size:16px;
    color:rgba(255,255,255,0.55); font-family:sans-serif;
  }
</style>
</head>
<body>
  <div class="canvas">
    <div class="banner">${headlineHtml}</div>
    ${bubblesHtml}
    ${paragraphHtml}
    ${badgeHtml}
    <div class="seq">${Number(imageSequence || 1)}/${Number(imageCount || 1)}</div>
  </div>
</body>
</html>`;
}

let browserPromise = null;
function getBrowser() {
  if (!browserPromise) {
    browserPromise = chromium.launch({ args: ["--no-sandbox"] });
  }
  return browserPromise;
}

app.post("/render", async (req, res) => {
  try {
    if (AUTH_TOKEN) {
      const got = (req.headers["authorization"] || "").replace(/^Bearer\s+/i, "");
      if (got !== AUTH_TOKEN) return res.status(401).json({ error: "UNAUTHORIZED" });
    }

    const {
      imageBase64,
      imageMimeType = "image/jpeg",
      design,
      headline,
      overlayText,
      imageSequence,
      imageCount,
    } = req.body || {};

    if (!imageBase64) return res.status(400).json({ error: "imageBase64 required" });
    if (!headline) return res.status(400).json({ error: "headline required" });
    if (!design) return res.status(400).json({ error: "design required" });

    const imageDataUrl = `data:${imageMimeType};base64,${imageBase64}`;
    const html = buildHtml({
      imageDataUrl,
      design,
      headline,
      overlayText: Array.isArray(overlayText) ? overlayText : [],
      imageSequence,
      imageCount,
    });

    const browser = await getBrowser();
    const page = await browser.newPage({ viewport: { width: 1080, height: 1080 } });
    try {
      await page.setContent(html, { waitUntil: "networkidle" });
      await page.evaluate(async () => {
        if (document.fonts && document.fonts.ready) await document.fonts.ready;
      });
      const buffer = await page.screenshot({ type: "png" });
      res.set("Content-Type", "image/png");
      res.send(buffer);
    } finally {
      await page.close();
    }
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "RENDER_FAILED", message: String(err.message || err) });
  }
});

app.get("/health", (_req, res) => res.json({ ok: true }));

app.listen(PORT, () => {
  console.log(`Beleaf render service listening on :${PORT}`);
});
